In [6]:
#assignmbet 2a 
#Coding problem : Find the eigenvalues and eigen vectors of the following matrix using Python. 

In [7]:
import numpy as np
# Define the matrix
matrix = np.array([[2, -1, 0],
                   [-1, 2, -1],
                   [0, -1, 2]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Display the results
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [3.41421356 2.         0.58578644]
Eigenvectors:
 [[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01  4.05405432e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]


In [8]:
#assignmbet 2b
#Coding problem : Find the eigenvalues and eigen vectors of the following matrix using Python. Verify that the received values indeed satisfy A.v = landa.v  

In [9]:
import numpy as np

# Define the matrix
A = np.array([[1, 2, 3],
              [3, 2, 1],
              [1, 0, -1]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display eigenvalues and eigenvectors
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Verify A * v = λ * v for each eigenvalue and eigenvector
for i in range(len(eigenvalues)):
    lambda_v = eigenvalues[i] * eigenvectors[:, i]
    A_v = np.dot(A, eigenvectors[:, i])
    print(f"\nEigenvalue {i + 1}: {eigenvalues[i]}")
    print(f"λ * v = {lambda_v}")
    print(f"A * v = {A_v}")
    print(f"Verification: {np.allclose(A_v, lambda_v)}")

   



Eigenvalues: [ 4.31662479e+00 -2.31662479e+00  1.93041509e-17]
Eigenvectors:
 [[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]

Eigenvalue 1: 4.3166247903554
λ * v = [2.52212416 3.47089307 0.47438446]
A * v = [2.52212416 3.47089307 0.47438446]
Verification: True

Eigenvalue 2: -2.3166247903554
λ * v = [-1.7049382   0.88492371  1.29493096]
A * v = [-1.7049382   0.88492371  1.29493096]
Verification: True

Eigenvalue 3: 1.9304150856667875e-17
λ * v = [ 7.88088659e-18 -1.57617732e-17  7.88088659e-18]
A * v = [-2.77555756e-16  2.22044605e-16  2.22044605e-16]
Verification: True
